name: Lint

on:
  workflow_call:

jobs:
  black:
    runs-on: ubuntu-latest
    name: black
    steps:
    - uses: actions/checkout@v1
    - name: black
      uses: docker://pyfound/black:23.3.0
      with:
        args: black --check python/src/bungeegum

  pylint:
    runs-on: ubuntu-latest
    name: pylint
    steps:
    - uses: actions/checkout@v1
    - name: pylint
      uses: docker://linedwell/pylint:py3
      with:
        args: pylint --disable=E0401 python/src/bungeegum

  mypy:
    runs-on: ubuntu-latest
    name: mypy
    steps:
    - uses: actions/checkout@v1
    - name: mypy
      uses: docker://ghcr.io/zetier/dockerized_mypy:3.8-1.3.0
      with:
        args: --config python/pyproject.toml python/src/bungeegum
